
variable "do_token" {
  type    = string
  default = "${env("DIGITALOCEAN_TOKEN")}"
}

// TODO Leverage DO Linux base image without manual pre-configuration
variable "base_image"{
  type    = string
  default = "142043191"
}

variable "version" {
  type    = string
  default = "VERSION-OF-YOUR-APP"
}

variable "size" {
  type    = string
  default = "s-1vcpu-1gb-intel"
}

variable "linux_user" {
  sensitive = true
  type  = string
  default = "admin"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "digitalocean" "autogenerated_1" {
  api_token     = "${var.do_token}"
  droplet_name  = "coscrad-backend-${var.version}"
  image         = "${var.base_image}"
  region        = "tor1"
  size          = "${var.size}"
  snapshot_name = "coscrad-backend-${var.version}-${local.timestamp}"
  ssh_username  = "root"
}

build {
  sources = ["source.digitalocean.autogenerated_1"]

  provisioner "shell" {
    inline = ["cloud-init status --wait"]
  }

  provisioner "file"{
    source = "./index.js"
    destination = "/tmp/"
  }

  provisioner "file"{
    source = "./scripts/startup.sh"
    destination = "/tmp/"
  }

// TODO provision admin user, patch system, install node, install nginx (currently prebuilt into base image manually)
  provisioner "shell" {
    environment_vars = ["LINUX_USER=${var.linux_user}"]
    scripts = ["scripts/copy-the-build.sh"]
  }
}
